name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']
        task: [default]
        include:
        # run rubocop against lowest supported ruby
        - ruby: '2.5'
          task: rubocop
    name: ruby${{ matrix.ruby }} rake ${{ matrix.task }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake ${{ matrix.task }}
